// Code generated by protoc-gen-go.
// source: src/meta/meta.proto
// DO NOT EDIT!

/*
Package meta is a generated protocol buffer package.

It is generated from these files:
	src/meta/meta.proto

It has these top-level messages:
	Message
*/
package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_TEXT    Message_Type = 0
	Message_SESSION Message_Type = 1
	Message_CONTROL Message_Type = 2
)

var Message_Type_name = map[int32]string{
	0: "TEXT",
	1: "SESSION",
	2: "CONTROL",
}
var Message_Type_value = map[string]int32{
	"TEXT":    0,
	"SESSION": 1,
	"CONTROL": 2,
}

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}
func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (x *Message_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_Type_value, data, "Message_Type")
	if err != nil {
		return err
	}
	*x = Message_Type(value)
	return nil
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message_Session_Type int32

const (
	Message_Session_OFFER          Message_Session_Type = 0
	Message_Session_ICE_CANDIDATE  Message_Session_Type = 1
	Message_Session_REJECT         Message_Session_Type = 2
	Message_Session_ANSWER         Message_Session_Type = 3
	Message_Session_ANSWER_CONFIRM Message_Session_Type = 4
	Message_Session_RINGING        Message_Session_Type = 5
	Message_Session_SHUTDOWN       Message_Session_Type = 6
)

var Message_Session_Type_name = map[int32]string{
	0: "OFFER",
	1: "ICE_CANDIDATE",
	2: "REJECT",
	3: "ANSWER",
	4: "ANSWER_CONFIRM",
	5: "RINGING",
	6: "SHUTDOWN",
}
var Message_Session_Type_value = map[string]int32{
	"OFFER":          0,
	"ICE_CANDIDATE":  1,
	"REJECT":         2,
	"ANSWER":         3,
	"ANSWER_CONFIRM": 4,
	"RINGING":        5,
	"SHUTDOWN":       6,
}

func (x Message_Session_Type) Enum() *Message_Session_Type {
	p := new(Message_Session_Type)
	*p = x
	return p
}
func (x Message_Session_Type) String() string {
	return proto.EnumName(Message_Session_Type_name, int32(x))
}
func (x *Message_Session_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_Session_Type_value, data, "Message_Session_Type")
	if err != nil {
		return err
	}
	*x = Message_Session_Type(value)
	return nil
}
func (Message_Session_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0, 0} }

type Message_Control_Type int32

const (
	Message_Control_REQUEST  Message_Control_Type = 0
	Message_Control_RESPONSE Message_Control_Type = 1
)

var Message_Control_Type_name = map[int32]string{
	0: "REQUEST",
	1: "RESPONSE",
}
var Message_Control_Type_value = map[string]int32{
	"REQUEST":  0,
	"RESPONSE": 1,
}

func (x Message_Control_Type) Enum() *Message_Control_Type {
	p := new(Message_Control_Type)
	*p = x
	return p
}
func (x Message_Control_Type) String() string {
	return proto.EnumName(Message_Control_Type_name, int32(x))
}
func (x *Message_Control_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_Control_Type_value, data, "Message_Control_Type")
	if err != nil {
		return err
	}
	*x = Message_Control_Type(value)
	return nil
}
func (Message_Control_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1, 0} }

type Message struct {
	Type      *Message_Type `protobuf:"varint,1,req,name=type,enum=meta.Message_Type" json:"type,omitempty"`
	Id        *string       `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	From      *string       `protobuf:"bytes,3,req,name=from" json:"from,omitempty"`
	FromAlias *string       `protobuf:"bytes,4,opt,name=fromAlias,def=" json:"fromAlias,omitempty"`
	Timestamp *int64        `protobuf:"varint,5,req,name=timestamp,def=0" json:"timestamp,omitempty"`
	Text      *string       `protobuf:"bytes,6,opt,name=text" json:"text,omitempty"`
	// Types that are valid to be assigned to Payloads:
	//	*Message_Session_
	//	*Message_Control_
	Payloads         isMessage_Payloads `protobuf_oneof:"payloads"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Message_Timestamp int64 = 0

type isMessage_Payloads interface {
	isMessage_Payloads()
}

type Message_Session_ struct {
	Session *Message_Session `protobuf:"bytes,7,opt,name=session,oneof"`
}
type Message_Control_ struct {
	Control *Message_Control `protobuf:"bytes,8,opt,name=control,oneof"`
}

func (*Message_Session_) isMessage_Payloads() {}
func (*Message_Control_) isMessage_Payloads() {}

func (m *Message) GetPayloads() isMessage_Payloads {
	if m != nil {
		return m.Payloads
	}
	return nil
}

func (m *Message) GetType() Message_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Message_TEXT
}

func (m *Message) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Message) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

func (m *Message) GetFromAlias() string {
	if m != nil && m.FromAlias != nil {
		return *m.FromAlias
	}
	return ""
}

func (m *Message) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return Default_Message_Timestamp
}

func (m *Message) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Message) GetSession() *Message_Session {
	if x, ok := m.GetPayloads().(*Message_Session_); ok {
		return x.Session
	}
	return nil
}

func (m *Message) GetControl() *Message_Control {
	if x, ok := m.GetPayloads().(*Message_Control_); ok {
		return x.Control
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Session_)(nil),
		(*Message_Control_)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// payloads
	switch x := m.Payloads.(type) {
	case *Message_Session_:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Session); err != nil {
			return err
		}
	case *Message_Control_:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Control); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Payloads has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 7: // payloads.session
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Session)
		err := b.DecodeMessage(msg)
		m.Payloads = &Message_Session_{msg}
		return true, err
	case 8: // payloads.control
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Control)
		err := b.DecodeMessage(msg)
		m.Payloads = &Message_Control_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// payloads
	switch x := m.Payloads.(type) {
	case *Message_Session_:
		s := proto.Size(x.Session)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Control_:
		s := proto.Size(x.Control)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Message_Session struct {
	Type              *Message_Session_Type `protobuf:"varint,1,req,name=type,enum=meta.Message_Session_Type" json:"type,omitempty"`
	OffererSessionId  *string               `protobuf:"bytes,2,req,name=offererSessionId" json:"offererSessionId,omitempty"`
	AnswererSessionId *string               `protobuf:"bytes,3,opt,name=answererSessionId" json:"answererSessionId,omitempty"`
	// Types that are valid to be assigned to SessionPayloads:
	//	*Message_Session_Offer_
	//	*Message_Session_AnswerConfirm_
	//	*Message_Session_Answer_
	//	*Message_Session_IceCandidate_
	//	*Message_Session_Reject_
	SessionPayloads  isMessage_Session_SessionPayloads `protobuf_oneof:"session_payloads"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *Message_Session) Reset()                    { *m = Message_Session{} }
func (m *Message_Session) String() string            { return proto.CompactTextString(m) }
func (*Message_Session) ProtoMessage()               {}
func (*Message_Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type isMessage_Session_SessionPayloads interface {
	isMessage_Session_SessionPayloads()
}

type Message_Session_Offer_ struct {
	Offer *Message_Session_Offer `protobuf:"bytes,4,opt,name=offer,oneof"`
}
type Message_Session_AnswerConfirm_ struct {
	AnswerConfirm *Message_Session_AnswerConfirm `protobuf:"bytes,5,opt,name=answerConfirm,oneof"`
}
type Message_Session_Answer_ struct {
	Answer *Message_Session_Answer `protobuf:"bytes,6,opt,name=answer,oneof"`
}
type Message_Session_IceCandidate_ struct {
	IceCandidate *Message_Session_IceCandidate `protobuf:"bytes,7,opt,name=iceCandidate,oneof"`
}
type Message_Session_Reject_ struct {
	Reject *Message_Session_Reject `protobuf:"bytes,8,opt,name=reject,oneof"`
}

func (*Message_Session_Offer_) isMessage_Session_SessionPayloads()         {}
func (*Message_Session_AnswerConfirm_) isMessage_Session_SessionPayloads() {}
func (*Message_Session_Answer_) isMessage_Session_SessionPayloads()        {}
func (*Message_Session_IceCandidate_) isMessage_Session_SessionPayloads()  {}
func (*Message_Session_Reject_) isMessage_Session_SessionPayloads()        {}

func (m *Message_Session) GetSessionPayloads() isMessage_Session_SessionPayloads {
	if m != nil {
		return m.SessionPayloads
	}
	return nil
}

func (m *Message_Session) GetType() Message_Session_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Message_Session_OFFER
}

func (m *Message_Session) GetOffererSessionId() string {
	if m != nil && m.OffererSessionId != nil {
		return *m.OffererSessionId
	}
	return ""
}

func (m *Message_Session) GetAnswererSessionId() string {
	if m != nil && m.AnswererSessionId != nil {
		return *m.AnswererSessionId
	}
	return ""
}

func (m *Message_Session) GetOffer() *Message_Session_Offer {
	if x, ok := m.GetSessionPayloads().(*Message_Session_Offer_); ok {
		return x.Offer
	}
	return nil
}

func (m *Message_Session) GetAnswerConfirm() *Message_Session_AnswerConfirm {
	if x, ok := m.GetSessionPayloads().(*Message_Session_AnswerConfirm_); ok {
		return x.AnswerConfirm
	}
	return nil
}

func (m *Message_Session) GetAnswer() *Message_Session_Answer {
	if x, ok := m.GetSessionPayloads().(*Message_Session_Answer_); ok {
		return x.Answer
	}
	return nil
}

func (m *Message_Session) GetIceCandidate() *Message_Session_IceCandidate {
	if x, ok := m.GetSessionPayloads().(*Message_Session_IceCandidate_); ok {
		return x.IceCandidate
	}
	return nil
}

func (m *Message_Session) GetReject() *Message_Session_Reject {
	if x, ok := m.GetSessionPayloads().(*Message_Session_Reject_); ok {
		return x.Reject
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message_Session) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_Session_OneofMarshaler, _Message_Session_OneofUnmarshaler, _Message_Session_OneofSizer, []interface{}{
		(*Message_Session_Offer_)(nil),
		(*Message_Session_AnswerConfirm_)(nil),
		(*Message_Session_Answer_)(nil),
		(*Message_Session_IceCandidate_)(nil),
		(*Message_Session_Reject_)(nil),
	}
}

func _Message_Session_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message_Session)
	// session_payloads
	switch x := m.SessionPayloads.(type) {
	case *Message_Session_Offer_:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Offer); err != nil {
			return err
		}
	case *Message_Session_AnswerConfirm_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AnswerConfirm); err != nil {
			return err
		}
	case *Message_Session_Answer_:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Answer); err != nil {
			return err
		}
	case *Message_Session_IceCandidate_:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IceCandidate); err != nil {
			return err
		}
	case *Message_Session_Reject_:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Reject); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message_Session.SessionPayloads has unexpected type %T", x)
	}
	return nil
}

func _Message_Session_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message_Session)
	switch tag {
	case 4: // session_payloads.offer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Session_Offer)
		err := b.DecodeMessage(msg)
		m.SessionPayloads = &Message_Session_Offer_{msg}
		return true, err
	case 5: // session_payloads.answerConfirm
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Session_AnswerConfirm)
		err := b.DecodeMessage(msg)
		m.SessionPayloads = &Message_Session_AnswerConfirm_{msg}
		return true, err
	case 6: // session_payloads.answer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Session_Answer)
		err := b.DecodeMessage(msg)
		m.SessionPayloads = &Message_Session_Answer_{msg}
		return true, err
	case 7: // session_payloads.iceCandidate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Session_IceCandidate)
		err := b.DecodeMessage(msg)
		m.SessionPayloads = &Message_Session_IceCandidate_{msg}
		return true, err
	case 8: // session_payloads.reject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Session_Reject)
		err := b.DecodeMessage(msg)
		m.SessionPayloads = &Message_Session_Reject_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_Session_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message_Session)
	// session_payloads
	switch x := m.SessionPayloads.(type) {
	case *Message_Session_Offer_:
		s := proto.Size(x.Offer)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Session_AnswerConfirm_:
		s := proto.Size(x.AnswerConfirm)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Session_Answer_:
		s := proto.Size(x.Answer)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Session_IceCandidate_:
		s := proto.Size(x.IceCandidate)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Session_Reject_:
		s := proto.Size(x.Reject)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Message_Session_SessionDescription struct {
	Sdp              *string `protobuf:"bytes,1,req,name=sdp" json:"sdp,omitempty"`
	Type             *string `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message_Session_SessionDescription) Reset()         { *m = Message_Session_SessionDescription{} }
func (m *Message_Session_SessionDescription) String() string { return proto.CompactTextString(m) }
func (*Message_Session_SessionDescription) ProtoMessage()    {}
func (*Message_Session_SessionDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

func (m *Message_Session_SessionDescription) GetSdp() string {
	if m != nil && m.Sdp != nil {
		return *m.Sdp
	}
	return ""
}

func (m *Message_Session_SessionDescription) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type Message_Session_Offer struct {
	Sdp              *Message_Session_SessionDescription `protobuf:"bytes,1,req,name=sdp" json:"sdp,omitempty"`
	Servers          []*Message_Session_Offer_IceServer  `protobuf:"bytes,2,rep,name=servers" json:"servers,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *Message_Session_Offer) Reset()                    { *m = Message_Session_Offer{} }
func (m *Message_Session_Offer) String() string            { return proto.CompactTextString(m) }
func (*Message_Session_Offer) ProtoMessage()               {}
func (*Message_Session_Offer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0, 1} }

func (m *Message_Session_Offer) GetSdp() *Message_Session_SessionDescription {
	if m != nil {
		return m.Sdp
	}
	return nil
}

func (m *Message_Session_Offer) GetServers() []*Message_Session_Offer_IceServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

type Message_Session_Offer_IceServer struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Username         *string `protobuf:"bytes,2,req,name=username" json:"username,omitempty"`
	Credential       *string `protobuf:"bytes,3,req,name=credential" json:"credential,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message_Session_Offer_IceServer) Reset()         { *m = Message_Session_Offer_IceServer{} }
func (m *Message_Session_Offer_IceServer) String() string { return proto.CompactTextString(m) }
func (*Message_Session_Offer_IceServer) ProtoMessage()    {}
func (*Message_Session_Offer_IceServer) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 1, 0}
}

func (m *Message_Session_Offer_IceServer) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Message_Session_Offer_IceServer) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Message_Session_Offer_IceServer) GetCredential() string {
	if m != nil && m.Credential != nil {
		return *m.Credential
	}
	return ""
}

type Message_Session_AnswerConfirm struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message_Session_AnswerConfirm) Reset()         { *m = Message_Session_AnswerConfirm{} }
func (m *Message_Session_AnswerConfirm) String() string { return proto.CompactTextString(m) }
func (*Message_Session_AnswerConfirm) ProtoMessage()    {}
func (*Message_Session_AnswerConfirm) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 2}
}

func (m *Message_Session_AnswerConfirm) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type Message_Session_Answer struct {
	Sdp              *Message_Session_SessionDescription `protobuf:"bytes,1,req,name=sdp" json:"sdp,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *Message_Session_Answer) Reset()                    { *m = Message_Session_Answer{} }
func (m *Message_Session_Answer) String() string            { return proto.CompactTextString(m) }
func (*Message_Session_Answer) ProtoMessage()               {}
func (*Message_Session_Answer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0, 3} }

func (m *Message_Session_Answer) GetSdp() *Message_Session_SessionDescription {
	if m != nil {
		return m.Sdp
	}
	return nil
}

type Message_Session_IceCandidate struct {
	Label            *int32  `protobuf:"varint,1,req,name=label" json:"label,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Candidate        *string `protobuf:"bytes,3,req,name=candidate" json:"candidate,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message_Session_IceCandidate) Reset()         { *m = Message_Session_IceCandidate{} }
func (m *Message_Session_IceCandidate) String() string { return proto.CompactTextString(m) }
func (*Message_Session_IceCandidate) ProtoMessage()    {}
func (*Message_Session_IceCandidate) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 4}
}

func (m *Message_Session_IceCandidate) GetLabel() int32 {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return 0
}

func (m *Message_Session_IceCandidate) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Message_Session_IceCandidate) GetCandidate() string {
	if m != nil && m.Candidate != nil {
		return *m.Candidate
	}
	return ""
}

type Message_Session_Reject struct {
	Reason           *string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message_Session_Reject) Reset()                    { *m = Message_Session_Reject{} }
func (m *Message_Session_Reject) String() string            { return proto.CompactTextString(m) }
func (*Message_Session_Reject) ProtoMessage()               {}
func (*Message_Session_Reject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0, 5} }

func (m *Message_Session_Reject) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type Message_Control struct {
	Type      *Message_Control_Type `protobuf:"varint,1,req,name=type,enum=meta.Message_Control_Type" json:"type,omitempty"`
	RequestId *string               `protobuf:"bytes,2,req,name=requestId" json:"requestId,omitempty"`
	// Types that are valid to be assigned to ControlPayloads:
	//	*Message_Control_Request_
	//	*Message_Control_Response_
	ControlPayloads  isMessage_Control_ControlPayloads `protobuf_oneof:"control_payloads"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *Message_Control) Reset()                    { *m = Message_Control{} }
func (m *Message_Control) String() string            { return proto.CompactTextString(m) }
func (*Message_Control) ProtoMessage()               {}
func (*Message_Control) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type isMessage_Control_ControlPayloads interface {
	isMessage_Control_ControlPayloads()
}

type Message_Control_Request_ struct {
	Request *Message_Control_Request `protobuf:"bytes,3,opt,name=request,oneof"`
}
type Message_Control_Response_ struct {
	Response *Message_Control_Response `protobuf:"bytes,4,opt,name=response,oneof"`
}

func (*Message_Control_Request_) isMessage_Control_ControlPayloads()  {}
func (*Message_Control_Response_) isMessage_Control_ControlPayloads() {}

func (m *Message_Control) GetControlPayloads() isMessage_Control_ControlPayloads {
	if m != nil {
		return m.ControlPayloads
	}
	return nil
}

func (m *Message_Control) GetType() Message_Control_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Message_Control_REQUEST
}

func (m *Message_Control) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *Message_Control) GetRequest() *Message_Control_Request {
	if x, ok := m.GetControlPayloads().(*Message_Control_Request_); ok {
		return x.Request
	}
	return nil
}

func (m *Message_Control) GetResponse() *Message_Control_Response {
	if x, ok := m.GetControlPayloads().(*Message_Control_Response_); ok {
		return x.Response
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message_Control) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_Control_OneofMarshaler, _Message_Control_OneofUnmarshaler, _Message_Control_OneofSizer, []interface{}{
		(*Message_Control_Request_)(nil),
		(*Message_Control_Response_)(nil),
	}
}

func _Message_Control_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message_Control)
	// control_payloads
	switch x := m.ControlPayloads.(type) {
	case *Message_Control_Request_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Request); err != nil {
			return err
		}
	case *Message_Control_Response_:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Response); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message_Control.ControlPayloads has unexpected type %T", x)
	}
	return nil
}

func _Message_Control_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message_Control)
	switch tag {
	case 3: // control_payloads.request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Control_Request)
		err := b.DecodeMessage(msg)
		m.ControlPayloads = &Message_Control_Request_{msg}
		return true, err
	case 4: // control_payloads.response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_Control_Response)
		err := b.DecodeMessage(msg)
		m.ControlPayloads = &Message_Control_Response_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_Control_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message_Control)
	// control_payloads
	switch x := m.ControlPayloads.(type) {
	case *Message_Control_Request_:
		s := proto.Size(x.Request)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Control_Response_:
		s := proto.Size(x.Response)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Message_Control_Request struct {
	ExpiresAt        *int64  `protobuf:"varint,1,opt,name=expiresAt,def=-1" json:"expiresAt,omitempty"`
	FireAndForget    *bool   `protobuf:"varint,2,opt,name=fireAndForget,def=0" json:"fireAndForget,omitempty"`
	IssuedTimestamp  *int64  `protobuf:"varint,3,opt,name=issuedTimestamp,def=0" json:"issuedTimestamp,omitempty"`
	Method           *string `protobuf:"bytes,4,req,name=method" json:"method,omitempty"`
	Parameters       *string `protobuf:"bytes,5,req,name=parameters" json:"parameters,omitempty"`
	Signature        *string `protobuf:"bytes,6,opt,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message_Control_Request) Reset()                    { *m = Message_Control_Request{} }
func (m *Message_Control_Request) String() string            { return proto.CompactTextString(m) }
func (*Message_Control_Request) ProtoMessage()               {}
func (*Message_Control_Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1, 0} }

const Default_Message_Control_Request_ExpiresAt int64 = -1
const Default_Message_Control_Request_FireAndForget bool = false
const Default_Message_Control_Request_IssuedTimestamp int64 = 0

func (m *Message_Control_Request) GetExpiresAt() int64 {
	if m != nil && m.ExpiresAt != nil {
		return *m.ExpiresAt
	}
	return Default_Message_Control_Request_ExpiresAt
}

func (m *Message_Control_Request) GetFireAndForget() bool {
	if m != nil && m.FireAndForget != nil {
		return *m.FireAndForget
	}
	return Default_Message_Control_Request_FireAndForget
}

func (m *Message_Control_Request) GetIssuedTimestamp() int64 {
	if m != nil && m.IssuedTimestamp != nil {
		return *m.IssuedTimestamp
	}
	return Default_Message_Control_Request_IssuedTimestamp
}

func (m *Message_Control_Request) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Message_Control_Request) GetParameters() string {
	if m != nil && m.Parameters != nil {
		return *m.Parameters
	}
	return ""
}

func (m *Message_Control_Request) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

type Message_Control_Response struct {
	Response         *string `protobuf:"bytes,1,req,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message_Control_Response) Reset()                    { *m = Message_Control_Response{} }
func (m *Message_Control_Response) String() string            { return proto.CompactTextString(m) }
func (*Message_Control_Response) ProtoMessage()               {}
func (*Message_Control_Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1, 1} }

func (m *Message_Control_Response) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "meta.Message")
	proto.RegisterType((*Message_Session)(nil), "meta.Message.Session")
	proto.RegisterType((*Message_Session_SessionDescription)(nil), "meta.Message.Session.SessionDescription")
	proto.RegisterType((*Message_Session_Offer)(nil), "meta.Message.Session.Offer")
	proto.RegisterType((*Message_Session_Offer_IceServer)(nil), "meta.Message.Session.Offer.IceServer")
	proto.RegisterType((*Message_Session_AnswerConfirm)(nil), "meta.Message.Session.AnswerConfirm")
	proto.RegisterType((*Message_Session_Answer)(nil), "meta.Message.Session.Answer")
	proto.RegisterType((*Message_Session_IceCandidate)(nil), "meta.Message.Session.IceCandidate")
	proto.RegisterType((*Message_Session_Reject)(nil), "meta.Message.Session.Reject")
	proto.RegisterType((*Message_Control)(nil), "meta.Message.Control")
	proto.RegisterType((*Message_Control_Request)(nil), "meta.Message.Control.Request")
	proto.RegisterType((*Message_Control_Response)(nil), "meta.Message.Control.Response")
	proto.RegisterEnum("meta.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterEnum("meta.Message_Session_Type", Message_Session_Type_name, Message_Session_Type_value)
	proto.RegisterEnum("meta.Message_Control_Type", Message_Control_Type_name, Message_Control_Type_value)
}

func init() { proto.RegisterFile("src/meta/meta.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0x6d, 0x8f, 0xdb, 0x44,
	0x10, 0xbe, 0xbc, 0xdb, 0x93, 0xbb, 0xab, 0xbb, 0xbc, 0x28, 0x32, 0xa5, 0x1c, 0x41, 0xad, 0x4e,
	0x05, 0x0e, 0x1a, 0x24, 0x24, 0x22, 0x24, 0x94, 0x26, 0x3e, 0x2e, 0x40, 0x13, 0x58, 0xa7, 0x2a,
	0x7c, 0x3a, 0x99, 0x78, 0x73, 0x18, 0x12, 0xdb, 0xec, 0x6e, 0xa0, 0xfd, 0x11, 0xfc, 0x13, 0xfe,
	0x0c, 0x9f, 0xf9, 0xc0, 0x5f, 0x61, 0xf6, 0x25, 0x76, 0x42, 0xd2, 0xfb, 0x82, 0x74, 0xba, 0xec,
	0xce, 0x3c, 0xcf, 0xec, 0xec, 0xcc, 0xb3, 0x63, 0x78, 0x4d, 0xf0, 0xf9, 0x47, 0x2b, 0x26, 0x23,
	0xfd, 0xef, 0x22, 0xe7, 0x99, 0xcc, 0x48, 0x5d, 0xad, 0xbb, 0x7f, 0xde, 0x81, 0xd6, 0x53, 0x26,
	0x44, 0x74, 0xc3, 0xc8, 0x43, 0xa8, 0xcb, 0x97, 0x39, 0xeb, 0x54, 0xce, 0xaa, 0xe7, 0xa7, 0x3d,
	0x72, 0xa1, 0xc1, 0xd6, 0x79, 0x31, 0x43, 0x0f, 0xd5, 0x7e, 0x72, 0x0a, 0xd5, 0x24, 0xee, 0x54,
	0x11, 0xe5, 0x52, 0x5c, 0x11, 0x02, 0xf5, 0x05, 0xcf, 0x56, 0x9d, 0x9a, 0xb6, 0xe8, 0x35, 0xb9,
	0x0f, 0xae, 0xfa, 0x1d, 0x2c, 0x93, 0x48, 0x74, 0xea, 0x67, 0x95, 0x73, 0xb7, 0x7f, 0x44, 0x4b,
	0x13, 0x79, 0x07, 0x5c, 0x99, 0xac, 0x98, 0x90, 0xd1, 0x2a, 0xef, 0x34, 0x90, 0x58, 0xeb, 0x57,
	0x3e, 0xa6, 0xa5, 0x4d, 0x05, 0x95, 0xec, 0x85, 0xec, 0x34, 0x15, 0x97, 0xea, 0x35, 0x79, 0x0c,
	0x2d, 0x81, 0xe9, 0x24, 0x59, 0xda, 0x69, 0xa1, 0xb9, 0xdd, 0x7b, 0x63, 0x37, 0xc7, 0xd0, 0x38,
	0xaf, 0x8e, 0xe8, 0x06, 0xa7, 0x28, 0xf3, 0x2c, 0x95, 0x3c, 0x5b, 0x76, 0x9c, 0x43, 0x94, 0xa1,
	0x71, 0x2a, 0x8a, 0xc5, 0xf9, 0x7f, 0x39, 0xd0, 0xb2, 0x91, 0xc8, 0xc5, 0x4e, 0x49, 0xfc, 0x83,
	0xc7, 0x6d, 0x97, 0xe6, 0x11, 0x78, 0xd9, 0x62, 0xc1, 0x38, 0xe3, 0xd6, 0x39, 0xde, 0x14, 0x6a,
	0xcf, 0x4e, 0x3e, 0x80, 0xbb, 0x51, 0x2a, 0x7e, 0xdf, 0x05, 0xd7, 0xf4, 0x75, 0xf7, 0x1d, 0xe4,
	0x13, 0x68, 0xe8, 0x08, 0xba, 0x98, 0xed, 0xde, 0x5b, 0x87, 0x53, 0x99, 0x2a, 0x08, 0x5e, 0xc6,
	0x60, 0xc9, 0xd7, 0x70, 0x62, 0x22, 0xe1, 0x35, 0x17, 0x09, 0x5f, 0x61, 0xa5, 0x15, 0xf9, 0xbd,
	0xc3, 0xe4, 0xc1, 0x36, 0x14, 0x83, 0xec, 0x72, 0xc9, 0xa7, 0xd0, 0x34, 0x06, 0xdd, 0x93, 0x76,
	0xef, 0xde, 0x6d, 0x51, 0x90, 0x6e, 0xd1, 0xe4, 0x0a, 0x8e, 0x93, 0x39, 0x1b, 0x46, 0x69, 0x9c,
	0xc4, 0x91, 0x64, 0xb6, 0x75, 0xdd, 0xc3, 0xec, 0xf1, 0x16, 0x12, 0x63, 0xec, 0x30, 0x55, 0x06,
	0x9c, 0xfd, 0xcc, 0xe6, 0xd2, 0xf6, 0xf2, 0x15, 0x19, 0x50, 0x8d, 0x51, 0x19, 0x18, 0xb4, 0xdf,
	0x07, 0x62, 0x7d, 0x23, 0x26, 0xe6, 0x3c, 0xc9, 0xa5, 0xea, 0xad, 0x07, 0x35, 0x11, 0xe7, 0xba,
	0xb5, 0x2e, 0x55, 0x4b, 0xad, 0x39, 0xd5, 0x6d, 0xd3, 0x31, 0xbd, 0xf6, 0xff, 0xa9, 0x40, 0x43,
	0x57, 0x95, 0xf4, 0x4b, 0x7c, 0xbb, 0x77, 0x7e, 0xf8, 0xe8, 0xfd, 0x63, 0x4c, 0xe4, 0x2f, 0x94,
	0x72, 0xf9, 0x6f, 0x8c, 0x0b, 0x0c, 0x5e, 0x43, 0xfe, 0x83, 0x5b, 0xfa, 0xa7, 0x8a, 0x10, 0x6a,
	0x34, 0xdd, 0xb0, 0xfc, 0x1f, 0xc0, 0x2d, 0xac, 0x2a, 0xf3, 0x35, 0x5f, 0x6e, 0x32, 0xc7, 0x25,
	0xf1, 0xc1, 0x59, 0x23, 0x34, 0x8d, 0x56, 0x9b, 0xec, 0x8b, 0x3d, 0x3e, 0x45, 0x98, 0x73, 0x16,
	0xb3, 0x54, 0x26, 0xd1, 0xd2, 0x3e, 0xd2, 0x2d, 0x8b, 0xff, 0x00, 0x4e, 0x76, 0x3a, 0x4f, 0x5e,
	0x87, 0x06, 0xe3, 0x3c, 0xe3, 0x78, 0x80, 0x12, 0xa3, 0xd9, 0xf8, 0x23, 0x68, 0x1a, 0xd8, 0xff,
	0x29, 0x84, 0x4f, 0xe1, 0x78, 0xbb, 0xc5, 0xea, 0xac, 0x65, 0xf4, 0x23, 0x33, 0x97, 0x69, 0x50,
	0xb3, 0xd9, 0x9b, 0x30, 0xf7, 0xc0, 0x9d, 0x17, 0xfa, 0x31, 0x37, 0x28, 0x0d, 0xfe, 0x19, 0x34,
	0x4d, 0xcb, 0xc9, 0x9b, 0x4a, 0x20, 0x91, 0xc0, 0xf9, 0x60, 0x52, 0xb7, 0xbb, 0xee, 0x2f, 0x50,
	0x57, 0x8f, 0x94, 0xb8, 0xd8, 0xcb, 0xcb, 0xcb, 0x80, 0x7a, 0x47, 0xe4, 0x2e, 0x9c, 0x8c, 0x87,
	0xc1, 0xf5, 0x70, 0x30, 0x19, 0x8d, 0x47, 0x83, 0x59, 0xe0, 0x55, 0x08, 0x60, 0x9c, 0xe0, 0xab,
	0x60, 0x38, 0xf3, 0xaa, 0x6a, 0x3d, 0x98, 0x84, 0xcf, 0x11, 0x5a, 0x43, 0x59, 0x9c, 0x9a, 0xf5,
	0xf5, 0x70, 0x3a, 0xb9, 0x1c, 0xd3, 0xa7, 0x5e, 0x9d, 0xb4, 0xa1, 0x45, 0xc7, 0x93, 0x2f, 0xf1,
	0xcf, 0x6b, 0x90, 0x63, 0x70, 0xc2, 0xab, 0x67, 0xb3, 0xd1, 0xf4, 0xf9, 0xc4, 0x6b, 0x3e, 0x21,
	0xe0, 0xd9, 0xe9, 0x73, 0x9d, 0x47, 0x2f, 0x97, 0x59, 0x14, 0x0b, 0xff, 0x8f, 0x3a, 0xb4, 0xec,
	0xa8, 0xb9, 0x7d, 0xa6, 0x58, 0xd0, 0xf6, 0x4c, 0xc1, 0xcb, 0x73, 0xf6, 0xeb, 0x1a, 0xe7, 0x62,
	0x31, 0x4c, 0x4a, 0x03, 0xf9, 0x0c, 0x5a, 0x76, 0xa3, 0x67, 0x47, 0xbb, 0xf7, 0xf6, 0xe1, 0x80,
	0xd4, 0x80, 0xd4, 0xa0, 0xb3, 0x78, 0xf2, 0x39, 0x38, 0x9c, 0x89, 0x3c, 0x4b, 0x05, 0xb3, 0x53,
	0xe5, 0xfe, 0xab, 0xb8, 0x06, 0x85, 0xe4, 0x82, 0xe1, 0xff, 0x5d, 0xc1, 0x12, 0xd8, 0x48, 0x67,
	0xe0, 0xb2, 0x17, 0x79, 0x82, 0xbe, 0x81, 0xd4, 0xa5, 0xaf, 0xf5, 0xab, 0x1f, 0x3e, 0xa6, 0xa5,
	0x91, 0xbc, 0x0f, 0x27, 0xa8, 0x2d, 0x36, 0x48, 0xe3, 0xcb, 0x8c, 0xdf, 0x30, 0x89, 0x17, 0xa9,
	0x9c, 0x3b, 0xfd, 0xc6, 0x22, 0x5a, 0x0a, 0x46, 0x77, 0x7d, 0x08, 0xbe, 0x93, 0x08, 0xb1, 0x66,
	0xf1, 0xac, 0xf8, 0x44, 0xd4, 0x74, 0x50, 0xfc, 0x44, 0xfc, 0xd7, 0xa3, 0x7a, 0x8e, 0x49, 0xff,
	0x94, 0xc5, 0x78, 0x07, 0x55, 0x1b, 0xbb, 0x53, 0xb2, 0xcf, 0x23, 0x8e, 0x0f, 0x40, 0xaa, 0x57,
	0xd7, 0x30, 0xb2, 0x2f, 0x2d, 0xaa, 0xac, 0x22, 0xb9, 0x49, 0x23, 0xb9, 0xe6, 0xcc, 0x7e, 0x65,
	0x4a, 0x83, 0xff, 0x10, 0x9c, 0xcd, 0xad, 0xd5, 0xe3, 0x2a, 0xea, 0x64, 0xde, 0x5c, 0xb1, 0xef,
	0xbe, 0x6b, 0x95, 0xa5, 0xf4, 0x10, 0x7c, 0xf7, 0x2c, 0x08, 0x67, 0xa8, 0x2d, 0xd4, 0x03, 0x0d,
	0xc2, 0x6f, 0xa7, 0x93, 0x10, 0x65, 0xa5, 0xf4, 0x60, 0x3f, 0x2d, 0x85, 0x1e, 0xba, 0x8f, 0x2c,
	0xcd, 0xc1, 0xdf, 0xe0, 0x7b, 0xc5, 0xc1, 0x00, 0x61, 0x10, 0x86, 0xe3, 0xe9, 0x04, 0x95, 0x88,
	0x1b, 0x94, 0xda, 0x8c, 0x4e, 0xbf, 0xf1, 0xaa, 0x4f, 0x00, 0x9c, 0x0d, 0xef, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc9, 0xd9, 0xaa, 0x9f, 0xca, 0x07, 0x00, 0x00,
}
